language: node_js
node_js:
  - '6'
script:
  - yarn run test
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g now

script:
  - yarn run build
  - rm build/static/js/main.*.js.map
  - now alias $(now --public --static ./build --token=$NOW_TOKEN) $URL_PROD --token=$NOW_TOKEN

